### ISSUE TITLE
httpx.ConnectTimeout: timed out

### ISSUE THREAD

**Issue by WavingCatDevs** [DemonKingSwarn/flix-cli#15]
**Metadata (please complete the following information)**
Version: latest
OS: Windows 10
Movie: N/A

**Describe the bug**
Downloading is broken.
It says the httpx connection has been timed out, please refer to the screenshot.

**Steps To Reproduce**

1. Run `flix-cli anymovie`
2. Choose any movie

**Expected behavior**
Downloading should work

![Capture](https://user-images.githubusercontent.com/69034430/229223360-989f7158-bc0e-4022-b12b-b38aca33056d.PNG)

**Comment by DemonKingSwarn** [comment]
httpx encountered the internet connection error while downloading.
