### ISSUE TITLE
Not working with some IDs

### ISSUE THREAD

**Issue by Prayag2** [DemonKingSwarn/flix-cli#2]
A lot of movies are working but some aren't. For example, entering the ID of most anime movies on IMDB and some other movies is giving this error:
```
Hand me the IMDB or, just press nothingness: tt6455162
Traceback (most recent call last):
  File "/home/prayag/Downloads/flix-cli/flix-cli.py", line 61, in <module>
    ).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by synacktraa** [comment]
It can only fetch movies ig, not series and episodes

**Comment by DemonKingSwarn** [comment]
> A lot of movies are working but some aren't. For example, entering the ID of most anime movies on IMDB and some other movies is giving this error:
> 
> ```
> Hand me the IMDB or, just press nothingness: tt6455162
> Traceback (most recent call last):
>   File "/home/prayag/Downloads/flix-cli/flix-cli.py", line 61, in <module>
>     ).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'
> ```

it should work now

**Comment by Prayag2** [comment]
AWESOME! You just made it like 10x better with the ability to search! Thanks :)
